# Generated by Django 3.0.6 on 2020-05-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(max_length=100)),
                ('idUsuario', models.CharField(max_length=100)),
                ('fecha_Baja', models.DateTimeField(max_length=100)),
                ('idActividad', models.CharField(max_length=100)),
                ('idRespuesta', models.CharField(max_length=100)),
                ('idResultado', models.CharField(max_length=100)),
            ],
        ),
    ]
