# Generated by Django 3.0.6 on 2020-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='idResultado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
