# Generated by Django 3.0.6 on 2020-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20200531_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='audio',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
